householddata <-read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings = "?")
data1 <- subset(householddata, Date %in% c("1/2/2007","2/2/2007"))
data1$Date <- as.Date(data1$Date, format="%d/%m/%Y")
dateplustime <- paste(as.Date(data1$Date), data1$Time)
data1$Dateplustime <- as.POSIXct(dateplustime)

par(mfrow=c(2,2))
png("plot4.png")
with(data1, (plot(Dateplustime,Global_active_power, type="l")))
with(data1, (plot(Dateplustime,Voltage, type="l")))
with(data1, (plot(Dateplustime,Sub_metering_1, type="l")))
lines(data1$Sub_metering_2 ~ data1$Dateplustime, col = 'Red')
lines(data1$Sub_metering_3 ~ data1$Dateplustime, col = 'Blue')
with(data1,(plot(Dateplustime,Global_reactive_power, type="l")))
dev.off()
