householddata <-read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings = "?")
data1 <- subset(householddata, Date %in% c("1/2/2007","2/2/2007"))
data1$Date <- as.Date(data1$Date, format="%d/%m/%Y")
dateplustime <- paste(as.Date(data1$Date), data1$Time)
data1$Dateplustime <- as.POSIXct(dateplustime)
png("plot2.png")
with(data1, {plot(Dateplustime,Global_active_power, type="l",ylab="Global Active Power (kilowatts)", xlab="")
})
dev.off()