householddata <-read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings = "?")
data1 <- subset(householddata, Date %in% c("1/2/2007","2/2/2007"))
data1$Date <- as.Date(data1$Date, format="%d/%m/%Y")
png("plot1.png")
hist(as.numeric(data1$Global_active_power), col="Red", main="Global Active Power", xlab="Global Active power (kilowatts)", ylab="Frequency")
dev.off()